#!/usr/bin/env python3
"""Validate the public pattern file and generate one shared C++ configuration."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def validate(data):
    def integer(value, low, high, label):
        if type(value) is not int or not low <= value <= high:
            raise ValueError(f"{label} must be an integer in {low}..{high}")
    integer(data["cooldown_ms"], 500, 60000, "cooldown_ms")
    integer(data["release_ms"], 300, 5000, "release_ms")
    patterns = data["patterns"]
    if not isinstance(patterns, list) or not 1 <= len(patterns) <= 16:
        raise ValueError("provide 1..16 patterns")
    names = []
    for p in patterns:
        name = p["name"]
        if not isinstance(name, str) or not re.fullmatch(r"[a-z][a-z0-9_]{0,23}", name):
            raise ValueError("pattern names: lowercase ASCII, max 24 characters")
        if name in names:
            raise ValueError("duplicate pattern name")
        names.append(name)
        if not isinstance(p["steps"], list) or not 1 <= len(p["steps"]) <= 32:
            raise ValueError("provide 1..32 steps")
        total = on = 0
        for step in p["steps"]:
            if not isinstance(step, list) or len(step) != 2:
                raise ValueError("each step is [duration_ms, amplitude]")
            duration, amplitude = step
            integer(duration, 1, 500, "duration_ms")
            integer(amplitude, 0, 230, "amplitude")
            total += duration
            on += duration if amplitude else 0
        if total > 3000 or not 1 <= on <= 1500:
            raise ValueError("pattern max 3000 ms total, 1..1500 ms motor on")
    if data["button_pattern"] not in names:
        raise ValueError("unknown button_pattern")
    if data["unknown_tag_pattern"] is not None and data["unknown_tag_pattern"] not in names:
        raise ValueError("unknown unknown_tag_pattern")
    if not isinstance(data["tags"], list) or len(data["tags"]) > 64:
        raise ValueError("max 64 tag bindings")
    uids = set()
    for tag in data["tags"]:
        uid = tag["uid"]
        if not isinstance(uid, str) or not re.fullmatch(r"(?:[0-9A-F]{8}|[0-9A-F]{14})", uid):
            raise ValueError("UID must be uppercase hex, 4 or 7 bytes")
        if uid in uids or tag["pattern"] not in names:
            raise ValueError("duplicate UID or unknown tag pattern")
        uids.add(uid)
    return names


def render(data):
    names = validate(data)
    out = ['// Generated by scripts/generate_config.py; edit config/patterns.json.',
           '#pragma once', '#include "haptic_core.h"', 'namespace config {',
           f'constexpr uint32_t kCooldownMs = {data["cooldown_ms"]};',
           f'constexpr uint32_t kReleaseMs = {data["release_ms"]};']
    for p in data["patterns"]:
        steps = ", ".join("{%d, %d}" % tuple(step) for step in p["steps"])
        out.append(f'const haptic::Step steps_{p["name"]}[] = {{{steps}}};')
    out.append('const haptic::Pattern kPatterns[] = {')
    for p in data["patterns"]:
        out.append(f'  {{"{p["name"]}", steps_{p["name"]}, {len(p["steps"])}}},')
    out += ['};', f'constexpr size_t kPatternCount = {len(names)};',
            f'constexpr size_t kButtonPattern = {names.index(data["button_pattern"])};',
            'const haptic::TagBinding kTags[] = {']
    # Sentinel allows a standard C++ array even when the bindings list is empty.
    for tag in data["tags"]:
        out.append(f'  {{"{tag["uid"]}", {names.index(tag["pattern"])}}},')
    out += ['  {nullptr, 0}', '};',
            f'constexpr size_t kTagCount = {len(data["tags"])};',
            'inline int patternByName(const char* name) {',
            '  for (size_t i = 0; i < kPatternCount; ++i)',
            '    if (std::strcmp(name, kPatterns[i].name) == 0) return int(i);',
            '  return -1;', '}',
            'inline int patternForTag(const char* uid) {',
            '  for (size_t i = 0; i < kTagCount; ++i)',
            '    if (std::strcmp(uid, kTags[i].uid) == 0) return int(kTags[i].pattern);']
    fallback = data["unknown_tag_pattern"]
    out += [f'  return {names.index(fallback) if fallback is not None else -1};',
            '}', '}  // namespace config', '']
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'include/generated_config.h'
    content = render(json.loads((ROOT / 'config/patterns.json').read_text()))
    if args.check:
        if not output.exists() or output.read_text() != content:
            raise SystemExit('generated_config.h is stale; run python3 scripts/generate_config.py')
        print('configuration validated; generated header is current')
    else:
        output.write_text(content)
        print('generated include/generated_config.h')


if __name__ == '__main__':
    main()
