// Generated by scripts/generate_config.py; edit config/patterns.json.
#pragma once
#include "haptic_core.h"
namespace config {
constexpr uint32_t kCooldownMs = 1000;
constexpr uint32_t kReleaseMs = 500;
const haptic::Step steps_hello[] = {{90, 180}, {100, 0}, {90, 180}};
const haptic::Step steps_heartbeat[] = {{70, 200}, {100, 0}, {160, 160}, {350, 0}};
const haptic::Step steps_celebrate[] = {{80, 160}, {80, 0}, {80, 190}, {80, 0}, {220, 220}};
const haptic::Pattern kPatterns[] = {
  {"hello", steps_hello, 3},
  {"heartbeat", steps_heartbeat, 4},
  {"celebrate", steps_celebrate, 5},
};
constexpr size_t kPatternCount = 3;
constexpr size_t kButtonPattern = 0;
const haptic::TagBinding kTags[] = {
  {"04A1B2C3D4E5F6", 1},
  {"DEADBEEF", 2},
  {nullptr, 0}
};
constexpr size_t kTagCount = 2;
inline int patternByName(const char* name) {
  for (size_t i = 0; i < kPatternCount; ++i)
    if (std::strcmp(name, kPatterns[i].name) == 0) return int(i);
  return -1;
}
inline int patternForTag(const char* uid) {
  for (size_t i = 0; i < kTagCount; ++i)
    if (std::strcmp(uid, kTags[i].uid) == 0) return int(kTags[i].pattern);
  return 0;
}
}  // namespace config
